import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="mx-4 my-4">
				<div className="font-bold text-4xl mx-12">
					<h1>Student Data Table</h1>
				</div>

				<div className="bg-white my-4 px-12 py-4 mx-12">
					<h2 className="mb-12">Filter Student Table By:</h2>
					<div className="grid grid-cols-3 gap-8 ">
						<div>
							<div>
								<span className="bg-white ml-8 z-10 -mt-8 block">Age</span>
							</div>
							<select className="input-select">
								<option value="DEFAULT">Select Age</option>
								<option value="products">Product</option>
								<option value="services">Services</option>
							</select>
						</div>

						<div>
							<div>
								<span className="bg-white ml-8 z-10 -mt-8 block">Age</span>
							</div>
							<select className="input-select">
								<option value="DEFAULT">Select Age</option>
								<option value="products">Product</option>
								<option value="services">Services</option>
							</select>
						</div>

						<div>
							<div>
								<span className="bg-white ml-8 z-10 -mt-8 block">Age</span>
							</div>
							<select className="input-select">
								<option value="DEFAULT">Select Age</option>
								<option value="products">Product</option>
								<option value="services">Services</option>
							</select>
						</div>
					</div>

					<div className="grid grid-cols-3 gap-8 my-12">
						<div>
							{/* <div>
								<span className="bg-white ml-8 z-10 -mt-8 block">Age</span>
							</div> */}
							<select className="input-select">
								<option value="DEFAULT">Select Age</option>
								<option value="products">Product</option>
								<option value="services">Services</option>
							</select>
						</div>

						<div className="">
							<button className="py-2 text-lg px-32 bg-green-600 rounded text-white w-full">
								search
							</button>
						</div>
					</div>
				</div>

				<div className="bg-white my-8 px-12 py-4 mx-12 overflow-y-scroll ">
					<div className="grid grid-cols-8 gap-4 mt-8 mb-4 bg-gray-200 py-2 px-4 font-bold">
						<div>
							<p>S/N</p>
						</div>
						<div>
							<p>Surname</p>
						</div>
						<div>
							<p>First Name</p>
						</div>
						<div>
							<p>Age</p>
						</div>
						<div>
							<p>Gender</p>
						</div>
						<div>
							<p>Level</p>
						</div>
						<div>
							<p>State</p>
						</div>
						<div>
							<p>Action</p>
						</div>
					</div>

					<div className="grid grid-cols-8 gap-4 my-2 border-b-2 py-2 px-4 ">
						<div>
							<p>01</p>
						</div>
						<div>
							<p>Chukwuma</p>
						</div>
						<div>
							<p>James</p>
						</div>
						<div>
							<p>24</p>
						</div>
						<div>
							<p>Male</p>
						</div>
						<div>
							<p>100 Level</p>
						</div>
						<div>
							<p>Ebonyi State</p>
						</div>
						<div>
							<button className="py-2 text-sm px-2 bg-green-600 rounded text-white">
								Download Result
							</button>
						</div>
					</div>

					<div className="grid grid-cols-8 gap-4 my-2 border-b-2 py-2 px-4 ">
						<div>
							<p>01</p>
						</div>
						<div>
							<p>Chukwuma</p>
						</div>
						<div>
							<p>James</p>
						</div>
						<div>
							<p>24</p>
						</div>
						<div>
							<p>Male</p>
						</div>
						<div>
							<p>100 Level</p>
						</div>
						<div>
							<p>Ebonyi State</p>
						</div>
						<div>
							<button className="py-2 text-sm px-2 bg-green-600 rounded text-white">
								Download Result
							</button>
						</div>
					</div>

					<div className="grid grid-cols-8 gap-4 my-2 border-b-2 py-2 px-4 ">
						<div>
							<p>01</p>
						</div>
						<div>
							<p>Chukwuma</p>
						</div>
						<div>
							<p>James</p>
						</div>
						<div>
							<p>24</p>
						</div>
						<div>
							<p>Male</p>
						</div>
						<div>
							<p>100 Level</p>
						</div>
						<div>
							<p>Ebonyi State</p>
						</div>
						<div>
							<button className="py-2 text-sm px-2 bg-green-600 rounded text-white">
								Download Result
							</button>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
